### ISSUE TITLE
Panic when file / folder is missing

### ISSUE THREAD

**Issue by qhga** [TheDonDope/gordle#5]
After running the executable it seems pretty worried about smth... 
Maybe a missing err != nil check? We will never find out! PLX HEEELP

```
panic: open /usr/share/dict/words: no such file or directory

goroutine 1 [running]:
github.com/TheDonDope/gordle/pkg/validation.readWords()
        /tmp/gordle/pkg/validation/guess.go:101 +0x9c
github.com/TheDonDope/gordle/pkg/validation.NewWotd()
        /tmp/gordle/pkg/validation/guess.go:75 +0x2b
main.main()
        /tmp/gordle/cmd/cli/main.go:19 +0x2e
 /tmp/gordle/cmd/cli
```

**Comment by TheDonDope** [comment]
Yeah this kinda sucks. For a linux system, e.g. debian based, on needs to `$ apt-get install wbritish` or `$ apt-get install wamerican` to install the dictionary required. I'll update the `README`, thanks for the hint!

**Comment by TheDonDope** [comment]
Should be fixed through f4cd45a3a99992043c1828b1a59b2a7303e8f9af

Could you `git pull` and verify plz?

**Comment by tossudev** [comment]
The program exits gracefully when the file is missing. However, no error message gets printed out to the user.
